apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <html>
      <head>
        <title>Welcome to NGINX 1st try!</title>
      </head>
      <body>
        <h1>Hello from NGINX!</h1>
      </body>
    </html>
