apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: nginx-log-pv
